# Basic compose to run wordpress / woocomerce

version: "3"

services:
  app:
    image: wordpress-nginx:1.24-0
    build:
      context: .
      dockerfile: image/nginx.dockerfile
    ports:
      - 80:8000
      - 443:8443
    volumes: &appvolumes
      - appdata:/var/www/html:delegated
    depends_on:
      - phpfpm
      - db

  db:
    platform: linux/x86_64 # mac os with m1 or change the image to mariadb
    # image: mariadb:10.5.8
    image: mysql:5.7.29
    restart: always
    ports:
      - 3306:3306
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql
     
  phpfpm:
    image: wordpress-phpfpm:8.0-0
    build:
      context: .
      dockerfile: image/php.dockerfile
    volumes: *appvolumes

volumes:
  dbdata:
  appdata: