# Basic compose to run wordpress / woocomerce

version: '3.6'

services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    env_file: env/db.env

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - 8080:80 # change to 80:80 when the shop is ready to go live
    restart: always
    env_file: env/wordpress.env
    volumes: &wordpressvolumes
      - ~/.composer:/var/www/.composer:cached
      - ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:cached
      - ~/.ssh/known_hosts:/var/www/.ssh/known_hosts:cached
      - wordpressdata:/var/www/html

  # mailcatcher:
  #   image: sj26/mailcatcher
  #   ports:
  #     - "1080:1080" 

volumes:
  dbdata:
  wordpressdata: