# Basic compose to run wordpress / woocomerce

version: "3"

services:
  app:
    volumes: &appvolumes
      - ./src:/var/www/html:cached
  
  db:
    restart: on-failure

  phpfpm:
    volumes: *appvolumes

  wp:
    image: wordpress-phpfpm-wp:8.0-0
    build:
      context: .
      dockerfile: image/wp-cli.dockerfile
    entrypoint: ['wp', '--allow-root']
    volumes: *appvolumes

  # sample with no container defined: 
  # > docker run -v "$PWD":/usr/src/app -w /usr/src/app node:4 npm install
  # bin/layout install -g node@12.18.3 
  # bin/layout install -g npm@9.8.0
  # bin/layout npm run-script watch
  # bin/layout i --prefix /var/www/html/wp-content/themes/chem-concepts
  layout:
    # image: node:20-alpine
    # image: node:12-alpine
    # image: node:12.18.3-alpine
    image: wordpress-node:12.18.3-0
    build:
      context: .
      dockerfile: image/node.dockerfile
    # platform: linux/amd64
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: /var/www/html/wp-content/themes/chem-concepts
    # entrypoint: ['npm']
    volumes: *appvolumes
  
